version: 2.1

jobs:
  build:
    docker:
      - image: codedarigan/godotsharp:latest

    steps:
        - checkout
        - run:
            name: "Run & Quit"
            command: godot -e -quit
        - run:
            name: "Delete .import files"
            command: rm addons/WAT/assets/*.import
        - run:
            name: "Run All Tests"
            command: godot addons/WAT/cli.tscn -run_all
        - store_test_results:
            path: tests/results
        - store_artifacts:
            path: tests/results

