version: 2.1

jobs:
  build:
    docker:
      - image: codedarigan/godotsharp:latest

    steps:
        - checkout
        - run:
            name: "Remove Local Import Files"
            command: rm addons/WAT/assets/*.import
        - run:
            name: "Open Once & Quit To ReImport Files"
            command: godot -e --quit
        - run:
            name: "Build Solution"
            command: godot --build-solutions
        - run:
            name: "Run All Tests"
            command: godot addons/WAT/cli.tscn -run_all
        - store_test_results:
            path: tests/results
        - store_artifacts:
            path: tests/results

