# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: push
  # Allows you to run this workflow manually from the Actions tab
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          nuget restore
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug
      - name: Compile
        run: msbuild
      - name: Run Tests
        run: godot addons/WAT/cli.tscn -run_all
